name: tcp_scanner
description: TCP port scanner. Scan ports sequentially using connect method.
version: 1.1.1
homepage: https://github.com/shpak86/tcp_scanner

environment:
  sdk: '>=2.5.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
